# Generated by Django 4.2.16 on 2024-11-17 01:29

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['search_vector'], name='posts_post_search__5398d0_idx'),
        ),
    ]
