# Generated by Django 4.2.16 on 2024-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post Test', max_length=255),
            preserve_default=False,
        ),
    ]
