# Generated by Django 4.2.16 on 2024-11-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_title'),
        ('posts', '0004_alter_comment_options_alter_comment_author_and_more'),
    ]

    operations = [
    ]
