# Generated by Django 4.2.16 on 2024-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_merge_20241124_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
