# Generated by Django 4.2.16 on 2024-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_post_hashtag_rel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geolocation', models.CharField(blank=True, max_length=100, null=True)),
                ('author_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
