# Generated by Django 4.2.16 on 2024-11-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
