# Generated by Django 4.2.16 on 2024-11-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('hashtags', '0004_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_hashtag_rel',
            name='hashtag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtags.hashtag'),
        ),
        migrations.AlterField(
            model_name='post_hashtag_rel',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
