# Generated by Django 4.2.16 on 2024-11-09 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('hashtags', '0005_alter_post_hashtag_rel_hashtag_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_hashtag_rel',
            new_name='PostHashtagRel',
        ),
    ]
